QUIT = 0
MAIN = 0
CREATE_TOURNAMENT = 1
RESUME_TOURNAMENT = 2
TOURNAMENTS_UPDATES = 3
PLAYERS_UPDATES = 4
REPORTS_MENU = 5
FILENAME_PLAYERS_LIST = 'players.json'
FILENAME_TOURNAMENTS_LIST = 'tournaments.json'
FRAME_LENGHT = 80
SPACE_REQUIRED = 5
NUMBER_SIDE_STARS = 1
STARS_LINE_FULL = "*"*FRAME_LENGHT
STARS_LINE = ('*'*NUMBER_SIDE_STARS +
              ' '*(FRAME_LENGHT - 2*NUMBER_SIDE_STARS) +
              '*'*NUMBER_SIDE_STARS)
TOP_DECORATION = "TOP"
BOTTOM_DECORATION = "BOTTOM"
